name: OWASP Depedency Scan

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  owasp-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      
      - name: Install Node Modules for Amplify Functions
        run: |
          if [ -d amplify/backend/function/accommodationFunction/src ]; then
            cd amplify/backend/function/accommodationFunction/src && npm install
            cd - # Go back to the previous directory
          fi
          if [ -d amplify/backend/function/locationSearchApi/src ]; then
            cd amplify/backend/function/locationSearchApi/src && npm install
            cd -
          fi
          if [ -d amplify/backend/function/recommendationHandler/src ]; then
            cd amplify/backend/function/recommendationHandler/src && npm install
            cd -
          fi
          if [ -d amplify/backend/function/geocodingHandler/src ]; then
            cd amplify/backend/function/geocodingHandler/src && npm install
            cd -
          fi

      - name: Install dependencies
        run: npm ci

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.3/dependency-check-10.0.3-release.zip
          unzip dependency-check-10.0.3-release.zip

      - name: Run OWASP Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh --project MyProject --out ./dependency-report --scan ./

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ./dependency-report/dependency-check-report.html